name = "LeanProfiler"
version = "0.1.0"
defaultTargets = ["leanprofiler"]

[[lean_lib]]
name = "LeanProfiler"

[[lean_lib]]
name = "test"
globs = ["test.+"]

[[lean_exe]]
name = "leanprofiler"
root = "Main"

[[lean_exe]]
name = "structured"
root = "test.Structured.Main"

[[lean_exe]]
name = "runtime-checks"
root = "test.RuntimeChecks.Main"

[[lean_lib]]
name = "Example"
globs = ["Example.+"]

[[lean_exe]]
name = "transformer-demo"
root = "Example.Main"
